(function() {
	var v = "1.7";
	if(window.jQuery === undefined || window.jQuery.fn.jquery < v) {
		var done = false;
		var script = document.createElement("script");
		script.src = "http://ajax.googleapis.com/ajax/libs/jquery/" + v + "/jquery.min.js";
		script.onload = script.onreadystatechange = function() {
			if(!done && (!this.readyState || this.readyState == "loaded" || this.readyState == "complete")) {
				done = true;
				initMyBookmarklet();
			}
		};
		document.getElementsByTagName("head")[0].appendChild(script);
	} else {
		initMyBookmarklet();
	}

	function initMyBookmarklet() {
		(window.myBookmarklet = function() {
			var equivalents = [
				['And it came to pass that',''],
				['And it shall come to pass that'],
				['And it shall come to pass'],
				['art','are'],
				['executeth','executed'],
				['asketh','ask'],
				['verily',''],
				['forth',''],
				['thine','your'],
				['Amen.',''],
				['Amen',''],
				['And now,',''],
				['graft','attach'],
				['the morrow','tomorrow'],
				['beheldest','saw'],
				['raiseth','raises'],
				['fighteth','fights'],
				['abhorreth','hates'],
				['labored','worked'],
				['draweth nigh','the is near'],
				['satisfieth','satifies'],
				['brethren','brothers'],
				['thirsteth','thirsts'],
				['doth','does'],
				['babes','babies'],
				['standeth','stands'],
				['pieces of their gold','gold coins'],
				['vineyard','garden'],
				['What mean ye?','What do you mean?'],
				['Ye','You'],
				['unto','to'],
				['saith:','says:'],
				['whoso','whoever'],
				['knocketh','knocks'],
				['commandeth','commands'],
				['behold',''],
				['Inasmuch as','if'],
				['concerning them','about them'],
				['cometh','comes'],
				['consecrate','set apart'],
				['delighteth','delights'],
				['fowls','birds'],
				['the fruit of my loins','my kin'],
				['the fruit of his loins','his kin'],
				['the fruit of your loins','your kin'],
				['giveth','gives'],
				['hath','has'],
				['very fine','very nice'],
				['I, Nephi,','I'],
				['assuredly','definitely'],
				['liveth','lives'],
				['did build','built'],
				['did preach','preached'],
				['did construct','constructed'],
				['after the manner of','just like'],
				['had made an end of','stopped'],
				['hast','have'],
				['thee','you'],
				['bowels','heart'],
				['bewitch','amaze'],
				['bruit','report'],
				['confounded','confused'],
				['comforteth','comforts'],
				['pondereth','thinks about'],
				['liberally','generously'],
				['spake','spoke'],
				['must needs','needs to'],
				['shalt','shall'],
				['seeketh','seeks'],
				['trow','think'],
				['thine','your'],
				['thou','you'],
				['thy','your'],
				['transgression','sin'],
				['nevertheless','still'],
				['transgressed','sinned'],
				['Thus saith the Lord God','This is what the Lord says'],
				['Thus saith the Lord','This is what the Lord says'],
				['saith the Lord','the Lord says'],
				['wherefore','therefore'],
				['upon','on'],
				['smitten','struck'],
				['bidden','instructed'],
				['exceedingly','greatly'],
				['O then',''],
				['sorroweth','grieves'],
				['bidden','grieves'],
				['slain','killed'],
				['great deep','ocean'],
				['yea,',''],
				['waketh,','wakes'],
				['weary','tired'],
				['Art thou','Are you'],
				['hath','has'],
				['thee','you'],
				['all flesh','all people'],
				['manifest','show'],
				['whence','where'],
				['somewhat concerning','about'],
				['mine','my'],
				['unto','to'],
				['For behold',''],
				['grieveth','grieves'],
				['yea',''],
				['utterly','entirely'],
				['wast','was'],
				['writeth','writes'],
				['wilt','will'],
				['mixeth','mixes'],
				['profit','advantage'],
				['ye','you'],
				['thereof',''],
				['save they shall','unless they'],
				['iniquities','sins'],
				['save it were','except it was'],
				['idle people','lazy people'],
				['years had passed away','years had gone by'],
				['thus far','so far'],
				['repent of their','turn from their'],
				['sufficeth me','is enough for me'],
				['contentions','fights'],
				['people of Nephi','Nephites'],
				['I am desirous for','I want the'],
				['And now, behold, ',''],
				['perish','die'],
				['likened to','made relevant to'],
				['for, for','for'],
				['relevant them','them relevant'],
				['beheld','saw'],
				['saidst','said'],
				['and thus','and'],
				['repent','turn'],
				['partaken','taken'],
				['sendeth','sends'],
				['provoketh','provokes'],
				['receiveth','receives'],
				['meet for repentance','fitting for repentance'],
				['manner after which','way'],
				['exceeding','great'],
				['an everlasting','a never-ending'],
				['everlasting','never-ending'],
				['remission','forgiveness'],
				['iniquity','sin'],
				['do iniquity','sin'],
				['converse','talks'],
				['repenteth','turns'],
				['hardeneth ','hardens'],
				['dieth','dies'],
				['whosoever','whoever'],
				['bar of God','courtroom of God'],
				['alike','like the'],
				['lesser portion','smaller part'],
				['even a','a'],
				['greater portion','bigger part'],
				['had a knowledge of','knew'],
				['abide','continue'],
				['as yet','so far'],
				['many riches','a lot of money'],
				['it thinks me that they','I think that they'],
				['hither','here'],
				['arouse','awake'],
				['justifieth','justifies'],
				['ascend','rises'],
				['sorrow','sadness'],
				['fornication','extra-marital sex'],
				['lasciviousness','lustfulness'],
				['mourning ','crying'],
				['condemneth','condemns'],
				['counseleth','counsels'],
				['you yourselves','you'],
				['abomination','ugly evil'],
				['will not suffer that','will not tolerate that'],
				['persist','stubbornly continue'],
				['appeareth','appears'],
				['speaketh','speaks'],
				['prophesieth','prophesies'],
				['marvel not',"don't be surprised"],
				['counsel the Lord','teach the Lord'],
				['take counsel from','learn from'],
				['healeth','heals'],
				['showeth','shows'],
				['of old','long ago'],
				['becometh','becomes'],
				['plainness','clarity'],
				['sought','looked'],
				['stiffnecked','stubborn'],
				['abominable','intensely ugly'],
				['causeth','causes'],
				['they needs to','they need to'],
				['burdeneth','burdens'],
				['before your wives','in front of your wives'],
				['grieves my soul','makes me sad'],
				['magnify my office','live up to my office'],
				['with soberness','with seriousn, clear thinking'],
				['knowest','know'],
				['hitherto','in the past'],
				['garments','clothing'],
				['sore battle','tough battle'],
				['exceed','surpass'],
				['quick and dead','living and dead'],
				['sitteth','sits'],
				['bit unto all','say to all'],
				['farewell','goodbye'],
				['adieu','goodbye'],
				['grant','give'],
				['plainly','clearly'],
				['continually','always'],
				['notwithstanding','still'],
				['depravity','evil'],
				['according to the knowledge which I have received','from what I learned'],
				['seemeth','seems'],
				['expound','explain'],
				['cast','throw'],
				['seal up','close'],
				['exhortation','sermon'],
				['more very','more'],
				['more and more','more'],
				['snare','trap'],
				['concerning','about'],
				['whatsoever','whatever'],
				['revile','speak negative things about'],
				['mightest','might'],
				['exhort','urge'],
				['seest','see'],
				['acknowledgeth','acknowledges'],
				['consciousness','awareness'],
				['O you',''],
				['made them known to me','taught me'],
				['See that you',''],
				['but one','one'],
				['all that I have written','all I wrote'],
				['saith','said'],
				['Now',''],
				['sayest','say'],
				['tremble','shake'],
				['temporal','temporary'],
				['disputations','arguments'],
				['astonished','surprised'],
				['inquired of the','asked the'],
				['about the matter','about it'],
				['solemn','serious'],
				['supposeth','thinks'],
				['a partial','an unfair'],
				['prophecies','inspired predictions'],
				['setteth at naught','nullifies'],
				['give heed','pay attention'],
				['availeth nothing','does nothing'],
				['denieth','denies'],
				['charity','love'],
				['speedily','quickly'],
				['severally','individually'],
				['shall do these things away','get rid of these things'],
				['beloved','loved'],
				['wo','trouble'],
				['bringeth','brings'],
				['I desire that you should','I want you to'],
				['both limb and joint','every part of the body'],
				['recollection','memory'],
				['the beholding of','the seeing of'],
				['tongues','languages'],
				['ministering spirits','servant-spirits'],
				['mighty','great'],
				['greatly great','very great'],
				['mattereth','matters'],
				['liken','compare'],
				[',',''],
				['Now,','']
			];
			$('p').each(function() {
				var x, html = $(this).html();
				for( x = 0; x < equivalents.length; x++) {
					html = html.split(" " + equivalents[x][0] + ' ').join(" " + equivalents[x][1] + ' ');
					html = html.split(" " + equivalents[x][0] + '.').join(" " + equivalents[x][1] + '.');
					html = html.split(" " + equivalents[x][0] + ',').join(" " + equivalents[x][1] + ',');
					html = html.split(" " + equivalents[x][0] + ';').join(" " + equivalents[x][1] + ';');
				}
				$(this).html(html);
			});
		})();
	}
})(); 